### ISSUE TITLE
ci build is failing

### ISSUE THREAD

**Issue by tewfik-ghariani** [tewfik-ghariani/nixops-grafana#1]
The build is currently failing while trying to fetch the '[grafana_api](https://github.com/m0nhawk/grafana_api)' python dependency

```
unpacking source archive /nix/store/ximp6z9w9w10f4jiilfq47wi261s4h0b-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/test/test_grafana.py
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "setup.py", line 8, in get_version
    ["git", "describe", "--tags", "--abbrev=0", "--match=[0-9]*"]
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 24, in <module>
    version=get_version(),
  File "setup.py", line 13, in get_version
    "The version number cannot be extracted from git tag in this source "
RuntimeError: The version number cannot be extracted from git tag in this source distribution; please either download the source from PyPI, or check out from GitHub and make sure that the git CLI is available.
builder for '/nix/store/nax1x07nq206hazqb2n5ykcfcs6q8hsg-python3.7-grafana-api-1.0.2.drv' failed with exit code 1
cannot build derivation '/nix/store/rm1afdnm6g20y8n2r180xlyhn1zrapr7-nixops_grafana-1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/rm1afdnm6g20y8n2r180xlyhn1zrapr7-nixops_grafana-1.0.drv' failed
```

More logs : https://github.com/tewfik-ghariani/nixops-grafana/runs/691507349

This appears to be the root cause but still not sure how to fix it...

```python
def get_version():
    try:
        tag = check_output(
            ["git", "describe", "--tags", "--abbrev=0", "--match=[0-9]*"]
        )
        return tag.decode("utf-8").strip("\n")
```

https://github.com/m0nhawk/grafana_api/blob/master/setup.py#L5

**Comment by tewfik-ghariani** [comment]
Fixed per https://github.com/tewfik-ghariani/nixops-grafana/commit/6a3c2eced8322837d36615f3a6d9d4c71148826f and https://github.com/tewfik-ghariani/nixops-grafana/pull/2

Closing,
